---
# File: security.yml
# Type: task
# Part: MySQL


- name: MySQL | Remove empty password users
  mysql_user: name="" password="" host=localhost priv=*.*:USAGE state=absent login_user=root login_password={{ mysql_root_password }}
- name: MySQL | Remove empty password users
  mysql_user: name="" password="" host={{ ansible_fqdn }} priv=*.*:USAGE state=absent login_user=root login_password={{ mysql_root_password }}
- name: MySQL | Remove the MySQL test database
  mysql_db: db=test state=absent login_user=root login_password={{ mysql_root_password }}

