---
# File: main.yml
# Type: task
# Part: Ansible/Setup


## Install
- name: Setup | Update aptitude
  apt: update_cache=yes cache_valid_time=3600
  tags: apt_update
- name: Setup | Install ansible required packages
  apt: name={{ item }} state=latest
  with_items:
    - python-apt
    - python-dev
    - python-pip
    - python-pycurl
    - python-software-properties
- name: Setup | Install ansible locally
  pip: name={{ item }} state=latest
  with_items:
    - ansible
- name: Setup | Install ansible locally
  shell: mkdir /etc/ansible; echo 'localhost ansible_connection=local' > /etc/ansible/hosts
         creates=/etc/ansible/hosts
